addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.5.18")
addSbtPlugin("org.irundaia.sbt" % "sbt-sassify" % "1.4.8")
addSbtPlugin("net.ground5hark.sbt" % "sbt-concat" % "0.1.9")
addSbtPlugin("com.typesafe.sbt" % "sbt-uglify" % "1.0.4")
addSbtPlugin("io.gatling" % "gatling-sbt" % "2.2.1")
